[project]
name = "autocard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.5",
    "dotenv>=0.9.9",
    "gunicorn>=25.3.0",
    "mlflow>=3.11.1",
    "numpy>=2.4.4",
    "pygame>=2.6.1",
    "python-socketio>=5.16.1",
    "torch>=2.11.0",
    "websocket-client>=1.9.0",
]
